### ISSUE TITLE
Ping should return the current bot ping

### ISSUE THREAD

**Issue by Daanisaanwezig** [Daanisaanwezig/mrMeeseeks#3]
## What is the problem
The ['ping'](https://github.com/Daanisaanwezig/mrMeeseeks/blob/master/commands/misc/ping.js) command currently only prints out a message saying pong.

### Expected behavior
The code should be changed so that it will display the ping, this can be done by comparing the time the message has been send with the current time.

**Comment by Chensokheng** [comment]
@Daanisaanwezig I am sorry. Can you give a an example for this one ? I don't get it.  🙏

**Comment by Daanisaanwezig** [comment]
Right now when I use the ping command it only responds with a message saying 'pong',
instead I want it to return something like 'Current ping: 20ms' in a nice embed. 
The ping in this case should be the bots ping to the discord api servers. If you have any other questions feel free to ask them.

**Comment by Chensokheng** [comment]
@Daanisaanwezig 
This is the sample message. if you agreed I will make a PR.  🙏
:ping_pong: Pong! Your Ping Is: 100ms

**Comment by Daanisaanwezig** [comment]
That should do the job, feel free to open a PR.
