### ISSUE TITLE
Add bad words to the list of forbidden words

### ISSUE THREAD

**Issue by Daanisaanwezig** [Daanisaanwezig/mrMeeseeks#8]
## What is the problem
The [automod](https://github.com/Daanisaanwezig/mrMeeseeks/blob/master/events/automod.js) currently does not filter any bad words because the list is empty.

### Expected behavior
The array should be filled with words that are NSFW, cursing or racist so that the auto moderator can do its work.

_*Please not that only adding 10 words will not be accepted for Hacktoberfest, this is a really simply issue so I at least expect some effort to be put in._

**Comment by divn** [comment]
I could give this a shot
